[package]
name = "lbsync"
version = "0.1.0"
authors = ["Felix Konstantin Maurer <maufl@maufl.de>"]

[dependencies]
reqwest = "0.8"
scraper = "0.6"
chrono = "0.4"
clap = "2"
uuid = { version = "0.6", features = ["v4"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
